{% set name = "vise" %}
{% set version = "0.9.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/vise-{{ version }}.tar.gz
  sha256: 7c92ba339d698f2623d3410a9831d113f9148900374cf0e509a0e718bcf77f95
  patches:
    - requirements.patch

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0
  entry_points:
    - vise = vise.cli.main:main
    - vise_util = vise.cli.main_util:main

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - mp-api
    - python >={{ python_min }}
    - pymatgen
    - seekpath
    - num2words
    - more-itertools
    - phonopy

test:
  imports:
    - vise
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/kumagai-group/vise
  summary: Package for handling io of vasp package in kumagai group at IMR, Tohoku university
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
