schema_version: 1

context:
  name: vise
  version: 0.9.6

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/vise-${{ version }}.tar.gz
  sha256: 239fa43bc05661b476ab536c7001bff8639e4b23a42f01f873ec33991a805c7a
  patches:
    - requirements.patch

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  python:
    entry_points:
      - vise = vise.cli.main:main
      - vise_util = vise.cli.main_util:main

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - setuptools
  run:
    - mp-api
    - python >=${{ python_min }}
    - seekpath
    - num2words
    - more-itertools
    - phonopy
    - pymatgen-core
tests:
  - python:
      imports:
        - vise
      pip_check: true
      python_version:
        - ${{ python_min }}
        - '*'

about:
  summary: Package for handling io of vasp package in kumagai group at IMR, Tohoku university
  license: MIT
  license_file: LICENSE
  homepage: https://github.com/kumagai-group/vise

extra:
  recipe-maintainers:
    - jan-janssen
